spring:
  application:
    name: transaction-service
  datasource:
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 8090
  servlet:
    context-path: /api/v1
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_INSTANCE_PORT}/eureka/