spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/api/v1/transactions/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/v1/accounts/**
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_INSTANCE_PORT}/eureka/