spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transaction-service
          uri: http://${TRANSACTIONS_SERVICE_HOST}:${TRANSACTIONS_SERVICE_PORT}
          predicates:
            - Path=/api/v1/transactions/**
        - id: accounts-service
          uri: http://${ACCOUNTS_SERVICE_HOST}:${ACCOUNTS_SERVICE_PORT}
          predicates:
            - Path=/api/v1/accounts/**
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_INSTANCE_PORT}/eureka/